export const GAMES_LIST_SUBSCRIBE = 'GAMES_LIST_SUBSCRIBE';
export const GAMES_LIST_UNSUBSCRIBE = 'GAMES_LIST_UNSUBSCRIBE';
export const GAMES_LIST_ADD_GAME = 'GAMES_LIST_ADD_GAME';
export const GAMES_LIST_CHANGE_GAME = 'GAMES_LIST_CHANGE_GAME';
export const GAMES_LIST_DELETE_GAME = 'GAMES_LIST_DELETE_GAME';
export const GAMES_LIST_CLEAR = 'GAMES_LIST_CLEAR';

export const JOIN_GAME = 'JOIN_GAME';
export const JOIN_GAME_START = 'JOIN_GAME_START';
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS';
export const JOIN_GAME_FAILED = 'JOIN_GAME_FAILED';

export const CREATE_GAME = 'CREATE_GAME';
export const CREATE_GAME_START = 'CREATE_GAME_START';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAILED = 'CREATE_GAME_FAILED';

export const GAME_SUBSCRIBE = 'GAME_SUBSCRIBE';
export const GAME_UNSUBSCRIBE = 'GAME_UNSUBSCRIBE';
export const GAME_UPDATE = 'GAME_UPDATE';
export const GAME_CLEAR = 'GAME_CLEAR';
export const GAME_ANSWER = 'GAME_ANSWER';
export const GAME_WAIT_TURN = 'GAME_WAIT_TURN';
export const GAME_FINISH = 'GAME_FINISH';

export const PLAYERS_SUBSCRIBE = 'PLAYERS_SUBSCRIBE';
export const PLAYERS_UNSUBSCRIBE = 'PLAYERS_UNSUBSCRIBE';
export const PLAYERS_ADD_PLAYER = 'PLAYERS_ADD_PLAYER';
export const PLAYERS_CHANGE_PLAYER = 'PLAYERS_CHANGE_PLAYER';

export const APP_ERROR = 'APP_ERROR';
export const APP_DELETE_ERRORS = 'APP_DELETE_ERRORS';

export const APP_LOADING_ON = 'APP_LOADING_ON';
export const APP_LOADING_OFF = 'APP_LOADING_OFF';

export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_AUTH = 'USER_AUTH';
