export const GAMES_LIST_SUBSCRIBE = 'GAMES_LIST_SUBSCRIBE';
export const GAMES_LIST_UNSUBSCRIBE = 'GAMES_LIST_UNSUBSCRIBE';
export const GAMES_LIST_CHANGE = 'GAMES_LIST_CHANGE';

export const JOIN_GAME = 'JOIN_GAME';
export const JOIN_GAME_START = 'JOIN_GAME_START';
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS';
export const JOIN_GAME_FAILED = 'JOIN_GAME_FAILED';

export const CREATE_GAME = 'CREATE_GAME';
export const CREATE_GAME_START = 'CREATE_GAME_START';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAILED = 'CREATE_GAME_FAILED';

export const GAME_WAIT_TURN = 'GAME_WAIT_TURN';
export const GAME_MOVE = 'GAME_MOVE';
export const GAME_FINISH = 'GAME_FINISH';

export const SCORE_CHANGED = 'SCORE_CHANGED';

export const APP_ERROR = 'APP_ERROR';
export const DELETE_APP_ERRORS = 'DELETE_APP_ERRORS';